version: '3.1'

services:
  db:
    image: mysql:5.7.21
    restart: always
    ports:
      - 3306:3306
  environment:
     MYSQL_DATABASE: test123
     MYSQL_USER: alen
     MYSQL_PASSWORD: password
     MYSQL_ROOT_PASSWORD: wordpress
  volumes:
     - ./.mysql_data:/var/www/alen-wp/wp-volume
     
